### ISSUE TITLE
ummm what

### ISSUE THREAD

**Issue by fgetcat** [SafinGames123/saturn-but-fully-compiled#1]
huh??

**Comment by SafinGames123** [comment]
I was unable to upload but it is on google drive

**Comment by fgetcat** [comment]
ok cool but like, i am one of the saturn devs, we can see when someone forks the repository

the reason why you need to compile saturn in the first place is because it relies on copyrighted assets from the mario 64 rom

these assets are, of course, owned by nintendo, so if we distributed a prebuilt exe nintendo would for sure take the whole project down

right now we're working on a system that would allow us to distribute a prebuilt exe, so theres no need for this repository to exist anyway. we already have an installer up and ready

now don't worry, we're not angry or anything, just saying
